name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    default: "22"
    required: false
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false
  registry:
    description: "Registry repo url"
    required: false
  registry_username:
    description: "Registry Username"
    required: false
  registry_password:
    description: "Registry Password"
    required: false
  registry_auth:
    description: "Activate registry authentication at deployment"
    default: false
    required: false
  prune:
    description: "Prune dangling services?"
    default: false
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
